require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StrategiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Strategy. As you add validations to Strategy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StrategiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all strategies as @strategies" do
      strategy = Strategy.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:strategies)).to eq([strategy])
    end
  end

  describe "GET #show" do
    it "assigns the requested strategy as @strategy" do
      strategy = Strategy.create! valid_attributes
      get :show, {:id => strategy.to_param}, valid_session
      expect(assigns(:strategy)).to eq(strategy)
    end
  end

  describe "GET #new" do
    it "assigns a new strategy as @strategy" do
      get :new, {}, valid_session
      expect(assigns(:strategy)).to be_a_new(Strategy)
    end
  end

  describe "GET #edit" do
    it "assigns the requested strategy as @strategy" do
      strategy = Strategy.create! valid_attributes
      get :edit, {:id => strategy.to_param}, valid_session
      expect(assigns(:strategy)).to eq(strategy)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Strategy" do
        expect {
          post :create, {:strategy => valid_attributes}, valid_session
        }.to change(Strategy, :count).by(1)
      end

      it "assigns a newly created strategy as @strategy" do
        post :create, {:strategy => valid_attributes}, valid_session
        expect(assigns(:strategy)).to be_a(Strategy)
        expect(assigns(:strategy)).to be_persisted
      end

      it "redirects to the created strategy" do
        post :create, {:strategy => valid_attributes}, valid_session
        expect(response).to redirect_to(Strategy.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved strategy as @strategy" do
        post :create, {:strategy => invalid_attributes}, valid_session
        expect(assigns(:strategy)).to be_a_new(Strategy)
      end

      it "re-renders the 'new' template" do
        post :create, {:strategy => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested strategy" do
        strategy = Strategy.create! valid_attributes
        put :update, {:id => strategy.to_param, :strategy => new_attributes}, valid_session
        strategy.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested strategy as @strategy" do
        strategy = Strategy.create! valid_attributes
        put :update, {:id => strategy.to_param, :strategy => valid_attributes}, valid_session
        expect(assigns(:strategy)).to eq(strategy)
      end

      it "redirects to the strategy" do
        strategy = Strategy.create! valid_attributes
        put :update, {:id => strategy.to_param, :strategy => valid_attributes}, valid_session
        expect(response).to redirect_to(strategy)
      end
    end

    context "with invalid params" do
      it "assigns the strategy as @strategy" do
        strategy = Strategy.create! valid_attributes
        put :update, {:id => strategy.to_param, :strategy => invalid_attributes}, valid_session
        expect(assigns(:strategy)).to eq(strategy)
      end

      it "re-renders the 'edit' template" do
        strategy = Strategy.create! valid_attributes
        put :update, {:id => strategy.to_param, :strategy => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested strategy" do
      strategy = Strategy.create! valid_attributes
      expect {
        delete :destroy, {:id => strategy.to_param}, valid_session
      }.to change(Strategy, :count).by(-1)
    end

    it "redirects to the strategies list" do
      strategy = Strategy.create! valid_attributes
      delete :destroy, {:id => strategy.to_param}, valid_session
      expect(response).to redirect_to(strategies_url)
    end
  end

end
